// @flow
export const departmentTags: {[string]: string} = {
  "Environment Agency": "Public body",
  "Health and Safety Executive": "Public body",
  "Department for Transport": "Public body",
  "Office for National Statistics": "Public body",
  "The National Archives": "Public body",
  "Home Office": "Public body",
  "Department for Environment Food and Rural Affairs": "Public body",
  "Cabinet Office": "Public body",
  "Department of Health": "Public body",
  "Met Office": "Public body",
  "HM Treasury": "Public body",
  "Department of the Environment": "Public body",
  "Department for Communities": "Public body",
  "Department for Education": "Public body",
  "Department for Communities and Local Government": "Public body",
  "Scottish Executive": "Devolved authority – Scotland",
  "National Audit Office": "Public body",
  "Transport for London": "London authority",
  "Ministry of Justice": "Public body",
  "The Highways Agency": "Public body",
  "Welsh Government": "Devolved authority – Wales",
  "Department for Work and Pensions": "Public body",
  "Office of the Deputy Prime Minister": "Public body",
  "Greater London Authority": "London authority",
  "Scottish Natural Heritage": "Devolved authority – Scotland",
  "Ministry of Defence": "Public body",
  "Natural England": "English authority",
  "Government Digital Service": "Public body",
  "Forestry Commission": "Public body",
  "Department of Transport": "Public body",
  "Department for International Development": "Public body",
  "Department of Energy and Climate Change": "Public body",
  "Scottish Environment Protection Agency": "Devolved authority – Scotland",
  "Office of Fair Trading": "Public body",
  ODPM: "Public body",
  "Department of Education": "Public body",
  "Crown Prosecution Service": "Public body",
  "Joint Nature Conservation Committee": "Public body",
  "HM Revenue & Customs": "Public body",
  GCHQ: "Public body",
  "Local Government Association": "Public body",
  DfES: "Public body",
  "Skills Funding Agency": "Public body",
  "The Scottish Government": "Devolved authority – Scotland",
  "Public Health England": "English authority",
  "London Fire Brigade": "Fire service",
  "Financial Conduct Authority": "Independent national body",
  "Companies House": "Public body",
  "Food Standards Agency": "Public body",
  "Competition Commission": "Public body",
  "Natural Resources Wales": "Devolved authority – Wales",
  "Office of Rail Regulation": "Public body",
  "Office of Public Sector Information": "Public body",
  "The Pensions Regulator": "Public body",
  "Serious Fraud Office": "Public body",
  "Foreign & Commonwealth Office": "Public body",
  "Department for Culture Media and Sport": "Public body",
  "City of London Corporation": "London authority",
  "The Technology Strategy Board": "Public body",
  "Driver and Vehicle Licensing Agency": "Public body",
  "Crown Commercial Service": "Public body",
  "Security Service": "Public body",
  "Department for Business, Enterprise and Regulatory Reform": "Public body",
  "Department for Business, Energy & Industrial Strategy": "Public body",
  "Charity Commission": "Public body",
  "Innovate UK": "Public body",
  "Defence Science and Technology Laboratory": "Public body",
  "General Register Office for Scotland": "Devolved authority – Scotland",
  "Office of Gas and Electricity Markets": "Public body",
  "Driving Standards Agency": "Public body",
  "Medicines and Healthcare Products Regulatory Agency": "Public body",
  "HM Land Registry": "Public body",
  "Vehicle Certification Agency": "Public body",
  "Office of Qualifications and Examinations Regulation": "Public body",
  "Wales Office": "Public body",
  "Northern Ireland Assembly": "Devolved authority – Northern Ireland",
  "Highlands and Islands Enterprise": "Devolved authority – Scotland",
  "Brecon Beacons National Park Authority": "National park authority",
  "UK Trade and Investment": "Public body",
  "Nuclear Decommissioning Authority": "Public body",
  "Improvement and Development Agency": "Public body",
  "The Health and Social Care Information Centre": "Public body",
  "Department For International Trade": "Public body",
  "Northern Ireland Housing Executive": "Devolved authority – Northern Ireland",
  "North London Waste Authority": "London authority",
  "Disclosure and Barring Service": "Public body",
  "Department of Finance": "Devolved authority – Northern Ireland",
  "Historic Scotland": "Devolved authority – Scotland",
  "Peak District National Park Authority": "National park authority",
  "Criminal Records Bureau": "Public body",
  "Gambling Commission": "Public body",
  "Registers of Scotland": "Devolved authority – Scotland",
  "Scotland Office": "Public body",
  "HM Prison Service": "Public body",
  "Arts Council England": "English authority",
  "Department of Education Northern Ireland":
    "Devolved authority – Northern Ireland",
  "Welsh Local Government Association": "Devolved authority – Wales",
  "Criminal Injuries Compensation Authority": "Public body",
  "Northern Ireland Office": "Public body",
  "Northern Ireland Statistics and Research Agency":
    "Devolved authority – Northern Ireland",
  "Serious Organised Crime Agency": "Public body",
  "Stabilisation Unit": "Public body",
  "Competition and Markets Authority": "Public body",
  "Fisheries Research Services": "Devolved authority – Scotland",
  "Convention of Scottish Local Authorities": "Devolved authority – Scotland",
  "National Records of Scotland": "Devolved authority – Scotland",
  "Education Scotland": "Devolved authority – Scotland",
  "Transport for Greater Manchester": "Public body",
  "Accountant in Bankruptcy": "Devolved authority – Scotland",
  "Criminal Cases Review Commission": "Public body",
  "HM Passport Office": "Public body",
  "The Patent Office": "Public body",
  "Office of Water Services": "Public body",
  "Debt Management Office": "Public body",
  "Single Source Regulations Office": "Public body",
  "Independent Police Complaints Commission": "Public body",
  "Government Actuary's Department": "Public body",
  "Food and Environment Research Agency": "Public body",
  "UK Sport": "Public body",
  "Office of the Advocate General": "Devolved authority – Scotland",
  "Council for Science and Technology": "Public body",
  "Judicial Appointments Board for Scotland": "Devolved authority – Scotland",
  "East London Waste Authority": "London authority",
  "Merseyside Fire and Rescue Service": "Fire service",
  "Driver & Vehicle Standards Agency": "Public body",
  "South Downs National Park Authority": "National park authority",
  "Office of the Immigration Services Commissioner": "Public body",
  "Lake District National Park Authority": "National park authority",
  "Department of Health Northern Ireland": "Devolved authority – Scotland",
  "West London Waste Authority": "London authority",
  "Crown Office and Procurator Fiscal Service": "Devolved authority – Scotland",
  "Glamorgan Record Office": "Public body",
  "The Northern Ireland Public Sector": "Devolved authority – Northern Ireland",
  "Legal Services Commission": "Public body",
  "Centre for the Protection of National Infrastructure": "Public body",
  "Child Support Agency": "Public body",
  "Northern Ireland Courts and Tribunals Service":
    "Devolved authority – Northern Ireland",
  "Essex County Fire & Rescue Service": "Fire service",
  "Local Government Data Unit ~ Wales": "Devolved authority – Wales",
  "Export Credits Guarantee Department": "Public body",
  "Northern Ireland Judicial Appointments Commission":
    "Devolved authority – Northern Ireland",
  "Her Majesty's Inspectorate of Constabulary": "Public body",
  "Greater Manchester Police": "Police force",
  "Wiltshire Police": "Police force",
  "Planning Inspectorate": "Public body",
  "Association of Greater Manchester Authorities":
    "Local government association",
  "West Midlands Fire Service": "Fire service",
  "Dartmoor National Park Authority": "National park authority",
  "Valuation Tribunal Service": "Public body",
  "Local Government Boundary Commission": "Public body",
  "National Association of Local Councils": "Local government association",
  "Exmoor National Park Authority": "National park authority",
};
