// @flow
export const departmentTags: {[string]: string} = {
  "Advisory Committee on Novel Foods and Processes":
    "NDPB with advisory functions",
  "Wilton Park": "Executive Agency",
  "Queen Elizabeth II Conference Centre": "Executive Agency",
  "Health Research Authority": "NDPB",
  "Information Commissioner�s Office": "NDPB",
  "Animals in Science Committee (ASC)": "NDPB with advisory functions",
  "UK Anti Doping": "NDPB",
  "Wallace Collection": "NDPB",
  "Her Majesty's Land Registry": "Non Ministerial Department",
  "Nuclear Research Advisory Council": "NDPB with advisory functions",
  "Civil Justice Council": "NDPB with advisory functions",
  "Theatres Trust": "NDPB with advisory functions",
  "Coal Authority": "NDPB",
  "Rural Payments Agency": "Executive Agency",
  "National Army Museum": "NDPB",
  "Planning Inspectorate": "Executive Agency",
  "Pension Protection Fund Ombudsman": "Tribunal NDPB",
  "Legal Aid Agency": "Executive Agency",
  "Parole Board of England and Wales": "NDPB",
  "UK Statistics Authority": "Non Ministerial Department",
  "Human Fertilisation and Embryology Authority": "NDPB",
  "United Kingdom Sports Council": "NDPB",
  "Pensions Advisory Service": "NDPB",
  "UK Debt Management Office": "Executive Agency",
  "National DNA Database Ethics Group (NDNADEG)":
    "NDPB with advisory functions",
  "Arts Council England": "NDPB",
  "Low Pay Commission": "NDPB with advisory functions",
  "Tribunal Procedure Committee": "NDPB with advisory functions",
  "Independent Agricultural Appeals Panel": "NDPB with advisory functions",
  "National Offender Management Service (NOMS)/ Her Majesty's Prison and Probation Service":
    "Executive Agency",
  "National Savings and Investments (NS&I)":
    "Non-Ministerial Department and Executive Agency (NS&I has dual status)",
  "Advisory Committee on Animal Feeding stuffs": "NDPB with advisory functions",
  "UK Hydrographic Office": "Executive Agency",
  "Plant Varieties and Seeds Tribunal": "Tribunal NDPB",
  "UK Space Agency": "Executive Agency",
  "Public Health England": "Executive Agency",
  "Office of the Public Guardian": "Executive Agency",
  "Criminal Cases Review Commission": "NDPB",
  "Centre for Environment, Fisheries and Aquaculture Science":
    "Executive Agency",
  "Office of Surveillance Commissioners": "Tribunal NDPB",
  "Senior Salaries Review Body": "NDPB with advisory functions",
  "National Crime Agency Remuneration Review Body":
    "NDPB with advisory functions",
  "Vehicle Certification Agency": "Executive Agency",
  "Committee on Fuel Poverty": "NDPB with advisory functions",
  "Economic and Social Research Council": "NDPB",
  "Treasure Valuation Committee": "NDPB with advisory functions",
  "Advisory Committee on Clinical Excellence Awards":
    "NDPB with advisory functions",
  "Traffic Commissioners for Great Britain": "Tribunal NDPB",
  "British Pharmacopoeia Commission": "NDPB with advisory functions",
  "Single Source Regulations Office (SSRO)": "NDPB",
  "Office of Rail and Road": "Non Ministerial Department",
  "National Crime Agency": "Non Ministerial Department",
  "Industrial Injuries Advisory Council": "NDPB with advisory functions",
  "Advisory Committee on Business Appointments": "NDPB with advisory functions",
  "Security Industry Authority": "NDPB",
  "Sport England": "NDPB",
  "Review Body on Doctors� and Dentists� Remuneration":
    "NDPB with advisory functions",
  "UK Atomic Energy Authority": "NDPB",
  "National Archives": "Non Ministerial Department",
  "Equality and Human Rights Commission": "NDPB",
  "Land Registration Rule Committee": "NDPB with advisory functions",
  "Her Majesty's Courts and Tribunals Service": "Executive Agency",
  "Independent Advisory Panel on Deaths in Custody":
    "NDPB with advisory functions",
  "Regional Advisory Committees / Forestry and Woodlands Advisory Committees (x9)":
    "NDPB with advisory functions",
  "Sports Grounds Safety Authority": "NDPB",
  "Government Internal Audit Agency (GIAA)": "Executive Agency",
  "Committee on Toxicity of Chemicals in Food, Consumer Products and the Environment":
    "NDPB with advisory functions",
  "Boundary Commission for Wales": "NDPB with advisory functions",
  "National Portrait Gallery": "NDPB",
  "Great Britain China�Centre": "NDPB",
  "Animal and Plant Health Agency": "Executive Agency",
  "Office of Gas and Electricity Markets (Ofgem)": "Non Ministerial Department",
  "House of Lords Appointments Commission": "NDPB with advisory functions",
  "British Transport Police Authority (BTPA)": "NDPB",
  "Engineering Construction Industry Training Board": "NDPB",
  "Science and Technology Facilities Council": "NDPB",
  "Boundary Commission for Scotland": "NDPB with advisory functions",
  "Committee on Mutagenicity of Chemicals in Food, Consumer Products and the Environment":
    "NDPB with advisory functions",
  "Arts and Humanities Research Council": "NDPB",
  "Student Loans Company": "NDPB",
  Tate: "NDPB",
  "Education Funding Agency": "Executive Agency",
  "Biotechnology and Biological Sciences Research Council": "NDPB",
  "Social Mobility Commission": "NDPB with advisory functions",
  "National College for Teaching and Leadership": "Executive Agency",
  "Advisory, Conciliation and Arbitration Service": "NDPB",
  "Health and Safety Executive": "NDPB",
  "Skills Funding Agency": "Executive Agency",
  "Standards and Testing Agency": "Executive Agency",
  "National Heritage Memorial Fund/Heritage Lottery Fund": "NDPB",
  "National Museum of the Royal Navy": "NDPB",
  "Royal Armouries": "NDPB",
  "Defence Electronics and Components Agency": "Executive Agency",
  "Advisory Committee on the Microbiological Safety of Food":
    "NDPB with advisory functions",
  "Copyright Tribunal": "Tribunal NDPB",
  "Committee on Standards in Public Life": "NDPB with advisory functions",
  "Prison Service Pay Review Body": "NDPB with advisory functions",
  "School Teachers� Review Body": "NDPB with advisory functions",
  "Boundary Commission for England": "NDPB with advisory functions",
  "British Council": "NDPB and  a non-financial public corporation",
  "Veterans Advisory and Pensions Committees": "NDPB with advisory functions",
  "Youth Justice Board for England and Wales": "NDPB",
  "National Employer Advisory Board": "NDPB with advisory functions",
  "Environment Agency": "NDPB",
  "Film Industry Training Board": "NDPB",
  "Judicial Appointments Commission": "NDPB",
  "Police Remuneration Review Body": "NDPB with advisory functions",
  "Social Science Research Committee": "NDPB with advisory functions",
  "Crown Prosecution Service": "Non Ministerial Department",
  "Office of the Immigration Services Commissioner": "NDPB",
  "Transport Focus": "NDPB",
  "Security Vetting Appeals Panel": "NDPB with advisory functions",
  "Trinity House": "NDPB",
  "Marine Management Organisation": "NDPB",
  "Insolvency Service": "Executive Agency",
  "Independent Commission for Aid Impact": "NDPB with advisory functions",
  "Civil Nuclear Police Authority": "NDPB",
  "Driver and Vehicle Licensing Agency (DVLA)": "Executive Agency",
  "Disabled People's Employment Corporation (GB) Ltd": "NDPB",
  "Independent Reconfiguration Panel": "NDPB with advisory functions",
  "Higher Education Funding Council for England": "NDPB",
  "Police Discipline Appeals Tribunal": "Tribunal NDPB",
  "British Museum": "NDPB",
  "Big Lottery Fund": "NDPB",
  "Medical Research Council": "NDPB",
  "Reviewing Committee on the Export of Works of Art":
    "NDPB with advisory functions",
  "Civil Service Commission": "NDPB",
  "NHS Improvement": "NDPB",
  "Gambling Commission": "NDPB",
  "Royal Museums Greenwich": "NDPB",
  "Forest Enterprise England": "Executive Agency",
  "The Pensions Regulator": "NDPB",
  "Commission on Human Medicines": "NDPB with advisory functions",
  "Sir John Soane's Museum": "NDPB",
  "Royal Mint Advisory Committee on the design of coins, medals, seals and decorations":
    "NDPB with advisory functions",
  "National Employment Savings Trust (NEST) Corporation":
    "NDPB and Public Corporation",
  "Competition and Markets Authority": "Non Ministerial Department",
  "Agriculture and Horticulture Development Board": "NDPB",
  "Migration Advisory Committee": "NDPB with advisory functions",
  "Office for Standards in Education, Children�s Services and Skills (OFSTED)":
    "Non Ministerial Department",
  "Disclosure and Barring Service": "NDPB",
  "Companies House": "Executive Agency",
  "Defence Nuclear Safety Committee": "NDPB with advisory functions",
  "Independent Police Complaints Commission": "NDPB",
  "Her Majesty's Revenue and Customs": "Non Ministerial Department",
  "Leasehold Advisory Service": "NDPB",
  "Building Regulations Advisory Committee": "NDPB with advisory functions",
  "Criminal Injuries Compensation Authority": "Executive Agency",
  "Office of Qualifications and Examinations Regulation (OFQUAL)":
    "Non Ministerial Department",
  "British Library": "NDPB",
  "Medicines and Healthcare products Regulatory Agency": "Executive Agency",
  "Commonwealth Scholarship Commission in the UK": "NDPB",
  "Advisory Council on the Misuse of Drugs (ACMD)":
    "NDPB with advisory functions",
  "Children and Family Court Advisory and Support Service": "NDPB",
  "Social Security Advisory Committee": "NDPB with advisory functions",
  "Horserace Betting Levy Board": "NDPB",
  "FCO Services": "Executive Agency",
  "Natural History Museum": "NDPB",
  "Veterinary Products Committee": "NDPB with advisory functions",
  "Independent Medical Expert Group": "NDPB with advisory functions",
  "Defence Science and Technology Laboratory": "Executive Agency",
  "Natural England": "NDPB",
  "National Institute for Health and Care Excellence": "NDPB",
  "Office of the Children�s Commissioner": "NDPB",
  "Investigatory Powers Tribunal": "Tribunal NDPB",
  "Family Justice Council": "NDPB with advisory functions",
  "Sea Fish Industry Authority": "NDPB",
  "Legal Services Board": "NDPB",
  "Law Commission of England and Wales": "NDPB with advisory functions",
  "Royal Air Force Museum": "NDPB",
  "Innovate UK": "NDPB",
  "Advisory Committee on Justices of the Peace (x44)":
    "NDPB with advisory functions",
  "Charity Commission for England and Wales": "Non Ministerial Department",
  "Sentencing Council for England and Wales": "NDPB with advisory functions",
  "Central Arbitration Committee": "Tribunal NDPB",
  "Science Advisory Committee on the Medical Implications of Less-Lethal Weapons":
    "NDPB with advisory functions",
  "National Gallery": "NDPB",
  "Armed Forces Pay Review Body": "NDPB with advisory functions",
  "Geffrye Museum": "NDPB",
  "Northern Lighthouse Board (Commissioners of Northern Lighthouses)": "NDPB",
  "Victoria and Albert Museum": "NDPB",
  "Forest Research": "Executive Agency",
  "National Infrastructure Commission": "Executive Agency",
  "Horniman Public Museum and Public Park Trust": "NDPB",
  "Forestry Commission": "Non Ministerial Department",
  "British Film Institute": "NDPB",
  "Committee on Radioactive Waste Management": "NDPB with advisory functions",
  "Commissioners for the Reduction of the National Debt":
    "Non Ministerial Department",
  "NHS Pay Review Body": "NDPB with advisory functions",
  "Care Quality Commission": "NDPB",
  "Government Legal Department": "Non Ministerial Department",
  "Joint Nature Conservation Committee": "NDPB",
  "NHS England": "NDPB",
  "Driver and Vehicle Standards Agency (DVSA)": "Executive Agency",
  "Science Advisory Council": "NDPB with advisory functions",
  "Veterinary Medicines Directorate": "Executive Agency",
  "Insolvency Rules Committee": "NDPB with advisory functions",
  "Boundary Commission for Northern Ireland": "NDPB with advisory functions",
  "Crown Commercial Service": "Executive Agency",
  "Serious Fraud Office": "Non Ministerial Department",
  "Consumer Council for Water": "NDPB",
  "Met Office": "Executive Agency",
  "Independent Monitoring Board for the Military Corrective Training Centre":
    "Other NDPB",
  "Construction Industry Training Board": "NDPB",
  "Valuation Tribunal for England": "Tribunal NDPB",
  VisitEngland: "NDPB with advisory functions",
  "Engineering and Physical Sciences Research Council": "NDPB",
  "Technical Advisory Board": "NDPB with advisory functions",
  "Marshall Aid Commemoration Commission": "NDPB",
  "Northern Ireland Human Rights Commission": "NDPB",
  "Advisory Committee on Conscientious Objectors":
    "NDPB with advisory functions",
  "Imperial War Museum": "NDPB",
  "Gangmasters and Labour Abuse Authority": "NDPB",
  "Criminal Procedure Rule Committee": "NDPB with advisory functions",
  "The Pensions Ombudsman": "Tribunal NDPB",
  "Civil Procedure Rule Committee": "NDPB with advisory functions",
  "Public Works Loan Board": "Non Ministerial Department",
  "Board of Trustees of the Royal Botanic Gardens Kew": "NDPB",
  "UK Supreme Court": "Non Ministerial Department",
  "Intellectual Property Office": "Executive Agency",
  "Health Education England": "NDPB",
  "Housing Ombudsman": "NDPB",
  "Office for Fair Access": "NDPB",
  "Directly Operated Railways Ltd": "NDPB",
  "High Speed 2 Ltd (HS2 Ltd)": "NDPB",
  "Competition Appeals Tribunal": "Tribunal NDPB",
  "Homes and Communities Agency": "NDPB",
  "Valuation Office Agency": "Executive Agency",
  "Office of Water Services (Ofwat)": "Non Ministerial Department",
  "Natural Environment Research Council": "NDPB",
  "Food Standards Agency": "Non Ministerial Department",
  "NHS Digital": "NDPB",
  "National Museums Liverpool": "NDPB",
  "Administration of Radioactive Substances Advisory Committee":
    "NDPB with advisory functions",
  "Valuation Tribunal Service": "NDPB",
  "Science Museum Group": "NDPB",
  "Nuclear Decommissioning Authority": "NDPB",
  "Committee on Climate Change": "NDPB",
  "Family Procedure Rule Committee": "NDPB with advisory functions",
  "Government Actuary's Department": "Non Ministerial Department",
  "Office for Budget Responsibility": "NDPB",
  "Westminster Foundation for Democracy": "NDPB",
  VisitBritain: "NDPB",
  "Human Tissue Authority": "NDPB",
  "Advisory Council on National Records and Archives":
    "NDPB with advisory functions",
  "Regulatory Policy Committee": "NDPB with advisory functions",
  "Maritime and Coastguard Agency (MCA)": "Executive Agency",
  "Advisory Committee on Releases to the Environment":
    "NDPB with advisory functions",
  "Competition Service": "NDPB",
  "British Hallmarking Council": "NDPB",
  "Ebbsfleet Development Corporation": "NDPB",
  "Nuclear Liabilities Financing Assurance Board":
    "NDPB with advisory functions",
  "Historic England ": "NDPB",
  "Parades Commission for Northern Ireland": "NDPB",
};
